package com.example.examen.controller;

import com.example.examen.service.ComunaService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.Banner;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Controller
public class AutoCompleteController {

    @Autowired
    ComunaService service;

    @GetMapping("/")
    public String home(Model model) {

        List<String> comunas = new ArrayList<>(Arrays.asList("Cerro Navia",
                "El Bosque",
                "Huechuraba",
                "La Cisterna",
                "La Granja",
                "La Reina",
                "Lo Barnechea",
                "Lo Prado",
                "Maipu",
                "Pedro Aguirre Cerda",
                "Providencia",
                "Quilicura",
                "Recoleta",
                "San Joaquin",
                "San Ramon",
                "Puente Alto",
                "Padre Hurtado",
                "El Monte",
                "San Pedro",
                "Curacavi",
                "Melipilla",
                "Calera de Tango",
                "San Bernardo",
                "Lampa",
                "San Jose de Maipo",
                "Peñaflor",
                "Isla de Maipo",
                "Talagante",
                "Maria Pinto",
                "Paine",
                "Buin",
                "Tiltil",
                "Colina",
                "Pirque",
                "Vitacura",
                "San Miguel",
                "Renca",
                "Quinta Normal",
                "Pudahuel",
                "Peñalolen",
                "ñuñoa",
                "Macul",
                "Lo Espejo",
                "Las Condes",
                "La Pintana",
                "La Florida",
                "Independencia",
                "Estacion Central",
                "Conchali",
                "Cerrillos",
                "Arica",
                "Camarones",
                "Putre",
                "General Lagos",
                "Iquique",
                "Alto Hospicio",
                "Pozo Almonte",
                "Camiña",
                "Colchane",
                "Huara",
                "Pica",
                "Antofagasta",
                "Mejillones",
                "Sierra Gorda",
                "Taltal",
                "Calama",
                "Ollague",
                "San Pedro de Atacama",
                "Maria Elena",
                "Tocopilla",
                "Copiapo",
                "Caldera",
                "Tierra Amarilla",
                "Chañaral",
                "Diego de Almagro",
                "Vallenar",
                "Alto del Carmen",
                "Freirina",
                "Huasco",
                "Rio Hurtado",
                "Monte Patria",
                "Ovalle",
                "Los Vilos",
                "Illapel",
                "Paiguano",
                "Andacollo",
                "La Serena",
                "Punitaqui",
                "Combarbala",
                "Salamanca",
                "Canela",
                "Vicuña",
                "La Higuera",
                "Coquimbo",
                "Valparaiso",
                "Concon",
                "Puchuncavi",
                "Los Andes",
                "Viña del Mar",
                "Rinconada",
                "La Ligua",
                "Papudo",
                "Zapallar",
                "Calera",
                "San Antonio",
                "Cartagena",
                "El Tabo",
                "San Felipe",
                "Llaillay",
                "La Cruz",
                "Villa Alemana",
                "Limache",
                "Putaendo",
                "Olmue",
                "Quilpue",
                "Santa Maria",
                "Panquehue",
                "Catemu",
                "Santo Domingo",
                "El Quisco",
                "Algarrobo",
                "Nogales",
                "Hijuelas",
                "Quillota",
                "Petorca",
                "Cabildo",
                "San Esteban",
                "Calle Larga",
                "Isla de Pascua",
                "Quintero",
                "Juan Fernandez",
                "Casablanca",
                "Rancagua",
                "Coinco",
                "Doñihue",
                "Las Cabras",
                "Malloa",
                "Olivar",
                "San Vicente",
                "Marchihue",
                "Paredones",
                "Chepica",
                "Lolol",
                "Palmilla",
                "Santa Cruz",
                "Placilla",
                "La Estrella",
                "Rengo",
                "Pichidegua",
                "Pumanque",
                "Peralillo",
                "Nancagua",
                "Chimbarongo",
                "San Fernando",
                "Navidad",
                "Litueche",
                "Pichilemu",
                "Requinoa",
                "Quinta de Tilcoco",
                "Peumo",
                "Mostazal",
                "Machali",
                "Graneros",
                "Coltauco",
                "Codegua",
                "Talca",
                "Curepto",
                "Maule",
                "Pencahue",
                "San Clemente",
                "Cauquenes",
                "Pelluhue",
                "Hualañe",
                "Molina",
                "Romeral",
                "Teno",
                "Linares",
                "Longavi",
                "Retiro",
                "Villa Alegre",
                "Constitucion",
                "Empedrado",
                "Pelarco",
                "Rio Claro",
                "San Rafael",
                "Curico",
                "Chanco",
                "Licanten",
                "Rauco",
                "Sagrada Familia",
                "Vichuquen",
                "Colbun",
                "Parral",
                "San Javier",
                "Yerbas Buenas",
                "Concepcion",
                "Chiguayante",
                "Hualqui",
                "Penco",
                "Santa Juana",
                "Tome",
                "Lebu",
                "Cañete",
                "Curanilahue",
                "Tirua",
                "Antuco",
                "Laja",
                "Nacimiento",
                "Quilaco",
                "San Rosendo",
                "Tucapel",
                "Alto Biobio",
                "Bulnes",
                "Coelemu",
                "Chillan Viejo",
                "Ninhue",
                "Pemuco",
                "Portezuelo",
                "Quirihue",
                "Treguaco",
                "San Ignacio",
                "San Carlos",
                "Yungay",
                "San Nicolas",
                "San Fabian",
                "Ranquil",
                "Quillon",
                "Pinto",
                "ñiquen",
                "El Carmen",
                "Coihueco",
                "Cobquecura",
                "Chillan",
                "Yumbel",
                "Santa Barbara",
                "Quilleco",
                "Negrete",
                "Mulchen",
                "Cabrero",
                "Los Angeles",
                "Los Alamos",
                "Contulmo",
                "Arauco",
                "Hualpen",
                "Talcahuano",
                "San Pedro de la Paz",
                "Lota",
                "Florida",
                "Coronel",
                "Temuco",
                "Cunco",
                "Freire",
                "Gorbea",
                "Loncoche",
                "Nueva Imperial",
                "Perquenco",
                "Pucon",
                "Teodoro Schmidt",
                "Vilcun",
                "Cholchol",
                "Collipulli",
                "Ercilla",
                "Los Sauces",
                "Puren",
                "Traiguen",
                "Carahue",
                "Curarrehue",
                "Galvarino",
                "Lautaro",
                "Padre Las Casas",
                "Pitrufquen",
                "Tolten",
                "Villarrica",
                "Angol",
                "Curacautin",
                "Lonquimay",
                "Lumaco",
                "Renaico",
                "Victoria",
                "Saavedra",
                "Melipeuco",
                "Valdivia",
                "Corral",
                "Lanco",
                "Los Lagos",
                "Mafil",
                "Mariquina",
                "Paillaco",
                "Panguipulli",
                "La Union",
                "Futrono",
                "Lago Ranco",
                "Rio Bueno",
                "Puerto Montt",
                "Cochamo",
                "Frutillar",
                "Puerto Varas",
                "Ancud",
                "Curaco de Velez",
                "Puqueldon",
                "Quellon",
                "Quinchao",
                "Puerto Octay",
                "Puyehue",
                "Hualaihue",
                "Chaiten",
                "San Juan de la Costa",
                "Llanquihue",
                "Calbuco",
                "Fresia",
                "Los Muermos",
                "Maullin",
                "Castro",
                "Queilen",
                "Quemchi",
                "Osorno",
                "Purranque",
                "Rio Negro",
                "San Pablo",
                "Futaleufu",
                "Palena",
                "Dalcahue",
                "Chonchi",
                "Coyhaique",
                "Aisen",
                "Guaitecas",
                "O'Higgins",
                "Chile Chico",
                "Verde",
                "Cisnes",
                "Cochrane",
                "Tortel",
                "Rio Ibañez",
                "Punta Arenas",
                "Rio Verde",
                "Cabo de Hornos (Ex-Navarino)",
                "Porvenir",
                "Timaukel",
                "Torres del Paine",
                "Natales",
                "Primavera",
                "Antartica",
                "San Gregorio",
                "Laguna Blanca"
                ));
        model.addAttribute("comunas", comunas);
        return "home";
    }

    @RequestMapping(value="/",method = RequestMethod.POST)
    public String report(Model model, @RequestParam String com){
        model.addAttribute("comuna", service.findAvistamientos(com));
        return "comuna";
    }
}